### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ghost** [danlevan/jquery.generic#6]
Hi Dan!
Love the work you're doing here..
I just wanted to mention that none of the examples are working, neither on Safari or Chrome..

**Comment by danlevan** [comment]
Sorry, I am actually making version 1.0.0 :)
should work in a few minutes

**Comment by lan3jur** [comment]
Ha, no worries! Take your time ;-)
And great job btw.. I’m gonna use a lot of your work on my new non-profit project :)

Have a nice day!

Jürgen Landrie

**Comment by danlevan** [comment]
Since it's a new version, there might be changes from the 0.x version. Not a lot of changes but still.
I'm trying to centralize my documentation + html so I might have broken some stuff.

Let me know if the examples are working now :)

**Comment by danlevan** [comment]
That's great :) and feel free to make changes to improve it. And if there are things that are not clear, let me know :D

**Comment by lan3jur** [comment]
Oh, I’m afraid my skills are not good enough yet to improve your work. I’d rather say I hope to be learning a lot from you :)

Since I’ve been trying out a few frameworks, I’ve seen a lot of messy code. That’s what I like your ‘Why another library’ section so much. I love to keep things separated and ‘clear’..

So for now, I’m going with jade, jquery and stylus.
Although I’m still trying to figure out the most flexible way to make templates with jade.. sometimes a get a bit confused with blocks and extends and includes and appends and such ;-)

Wish there were more hours in a day to combine study and work on my non-profit educational project / platform and try to make some money meanwhile :)

Anyway, don’t want to bore you too much.. :)

cheers,
/jurgen

**Comment by lan3jur** [comment]
Examples are working peachy!!
Great stuff there… :)

cheers
/jurgen

**Comment by danlevan** [comment]
great :)
